# Backend Deploy

version: '3'
services:
  # Nginx
  nginx:
    platform: linux/amd64
    image: wingit_backend_nginx:v0.0.1
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on: # Service Dependencies (Container init order)
      - web
    hostname: WingItNginx

  # Django Application
  web:
    platform: linux/amd64
    image: wingit_backend_app:v0.0.5
    build:
      context: .
      dockerfile: Dockerfile
    hostname: WingItApp