# Generated by Django 5.1.1 on 2024-11-17 15:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('exam', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.teacher'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.teacher'),
        ),
        migrations.CreateModel(
            name='SolvedExam',
            fields=[
                ('solved_exam_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('time', models.DurationField()),
                ('score', models.IntegerField(null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.student')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('solved_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='exam.solvedexam')),
            ],
        ),
        migrations.CreateModel(
            name='SolvedProb',
            fields=[
                ('solved_prob_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('solution', models.ImageField(upload_to='solution')),
                ('response', models.CharField(blank=True, max_length=512, null=True)),
                ('correctness', models.BooleanField(null=True)),
                ('prob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.prob')),
                ('solved_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='exam.solvedexam')),
            ],
        ),
        migrations.AddConstraint(
            model_name='solvedexam',
            constraint=models.UniqueConstraint(fields=('exam', 'student'), name='unique_solved_exam'),
        ),
        migrations.AddConstraint(
            model_name='solvedprob',
            constraint=models.UniqueConstraint(fields=('solved_exam', 'solved_prob_id'), name='unique_solved_prob'),
        ),
    ]
