# Generated by Django 5.1.1 on 2024-11-19 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_alter_category_creator_alter_exam_creator_solvedexam_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='explanation',
        ),
    ]
