# Generated by Django 5.1.1 on 2024-11-27 04:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_remove_exam_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='solvedexam',
            name='solved_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
