# Generated by Django 5.1.1 on 2024-11-27 04:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_solvedexam_solved_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='prob',
            name='difficulty',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
            preserve_default=False,
        ),
    ]
