# Generated by Django 5.1.1 on 2024-12-01 09:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_prob_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='is_recommended',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='prob',
            name='difficulty',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
