# Generated by Django 5.1.1 on 2024-12-02 05:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_alter_exam_creator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamProb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prob_seq', models.IntegerField()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='prob',
            name='unique_prob',
        ),
        migrations.RemoveField(
            model_name='prob',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='prob',
            name='prob_seq',
        ),
        migrations.AddField(
            model_name='prob',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examprob',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.exam'),
        ),
        migrations.AddField(
            model_name='examprob',
            name='prob',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.prob'),
        ),
        migrations.AddField(
            model_name='exam',
            name='problems',
            field=models.ManyToManyField(related_name='exams', through='exam.ExamProb', to='exam.prob'),
        ),
    ]
