# Generated by Django 5.1.1 on 2024-12-02 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_examprob_remove_prob_unique_prob_remove_prob_exam_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='examprob',
            constraint=models.UniqueConstraint(fields=('exam', 'prob_seq'), name='unique_seq'),
        ),
    ]
