# Generated by Django 5.1.1 on 2024-12-02 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_examprob_unique_seq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solvedprob',
            name='solution',
            field=models.TextField(),
        ),
    ]
