# Generated by Django 5.1.1 on 2024-12-02 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('exam', '0010_alter_solvedprob_solution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prob',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.teacher'),
        ),
    ]
