# Generated by Django 5.1.1 on 2024-12-10 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0011_alter_prob_creator'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='solvedexam',
            name='unique_solved_exam',
        ),
    ]
