# Generated by Django 5.1.1 on 2024-12-12 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0012_remove_solvedexam_unique_solved_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='solvedprob',
            name='time',
            field=models.DurationField(default=0),
            preserve_default=False,
        ),
    ]
