# Generated by Django 5.1.1 on 2024-12-12 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0014_alter_solvedprob_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('prob_seq', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('solved_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='exam.solvedexam')),
            ],
        ),
    ]
