# Generated by Django 5.1.1 on 2024-12-12 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0015_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='timestamp',
        ),
    ]
