# Generated by Django 5.1.1 on 2024-12-12 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0017_log_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='timestamp',
            field=models.CharField(max_length=255),
        ),
    ]
