# Generated by Django 5.1.1 on 2024-12-12 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0018_alter_log_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='solved_exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.solvedexam'),
        ),
    ]
