name: Deployment
on:
  push:
    branches: ["dev"]

jobs:
  deploy:
    uses: tronze/useful-workflows/.github/workflows/s3-cloudfront-deploy.yml@main
    with:
      NODE_VERSION: v18.13.0
      S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
      CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      BUILD_COMMAND: yarn build
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
